/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedPaymentsIdRouteImport } from './routes/_authenticated/payments.$id'
import { Route as ApiPublicBootstrapStaffRouteImport } from './routes/api/public/bootstrap-staff'
import { Route as ApiPublicMondayRetryRouteImport } from './routes/api/public/monday-retry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIdRoute = AuthenticatedPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPaymentsRoute,
} as any)
const ApiPublicBootstrapStaffRoute = ApiPublicBootstrapStaffRouteImport.update({
  id: '/api/public/bootstrap-staff',
  path: '/api/public/bootstrap-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMondayRetryRoute = ApiPublicMondayRetryRouteImport.update({
  id: '/api/public/monday-retry',
  path: '/api/public/monday-retry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/api/public/bootstrap-staff': typeof ApiPublicBootstrapStaffRoute
  '/api/public/monday-retry': typeof ApiPublicMondayRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/api/public/bootstrap-staff': typeof ApiPublicBootstrapStaffRoute
  '/api/public/monday-retry': typeof ApiPublicMondayRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/api/public/bootstrap-staff': typeof ApiPublicBootstrapStaffRoute
  '/api/public/monday-retry': typeof ApiPublicMondayRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/request'
    | '/audit'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/vendors'
    | '/payments/$id'
    | '/api/public/bootstrap-staff'
    | '/api/public/monday-retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/request'
    | '/audit'
    | '/dashboard'
    | '/payments'
    | '/profile'
    | '/vendors'
    | '/payments/$id'
    | '/api/public/bootstrap-staff'
    | '/api/public/monday-retry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/request'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/vendors'
    | '/_authenticated/payments/$id'
    | '/api/public/bootstrap-staff'
    | '/api/public/monday-retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RequestRoute: typeof RequestRoute
  ApiPublicBootstrapStaffRoute: typeof ApiPublicBootstrapStaffRoute
  ApiPublicMondayRetryRoute: typeof ApiPublicMondayRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/$id': {
      id: '/_authenticated/payments/$id'
      path: '/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AuthenticatedPaymentsIdRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/api/public/bootstrap-staff': {
      id: '/api/public/bootstrap-staff'
      path: '/api/public/bootstrap-staff'
      fullPath: '/api/public/bootstrap-staff'
      preLoaderRoute: typeof ApiPublicBootstrapStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monday-retry': {
      id: '/api/public/monday-retry'
      path: '/api/public/monday-retry'
      fullPath: '/api/public/monday-retry'
      preLoaderRoute: typeof ApiPublicMondayRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsIdRoute: typeof AuthenticatedPaymentsIdRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsIdRoute: AuthenticatedPaymentsIdRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RequestRoute: RequestRoute,
  ApiPublicBootstrapStaffRoute: ApiPublicBootstrapStaffRoute,
  ApiPublicMondayRetryRoute: ApiPublicMondayRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
